### ISSUE TITLE
Can't add snipets

### ISSUE THREAD

**Issue by paulmarshall** [sam-cogan/arm-snippets-vscode#2]
Just installed v1.10, created a new JSON file, entered "arm!".

If I use "arm-pararm", the text appears red and tabbing beyond this does nothing

**Comment by sam-cogan** [comment]
Hi Paul, if you just type "arm" do you see the full list of options:

![2018-03-12_22-56-35](https://user-images.githubusercontent.com/26353048/37313788-a6e69a3e-2648-11e8-8c8a-ddb8cb53c63f.png)

It should just be a case of selecting the one you want and hitting enter. Do other snippet extensions work for you? We're not doing anything special here compared to other snippet extensions
