### ISSUE TITLE
Add new Snippets and update snippets to newer apiversions 

### ISSUE THREAD

**Issue by kilasuit** [sam-cogan/arm-snippets-vscode#4]
I've been using this extension and noticed that some of the snippets are out of date to recent version changes to the apiVersions of things like publicIPAddresses as an example

**Comment by sam-cogan** [comment]
Yeah, they do need a bit of going over to update them. I'll look to do this over the next few weeks.

**Comment by sam-cogan** [comment]
API versions are now up to date.
