### ISSUE TITLE
Comma misplaced in 'arm-stg' snippet

### ISSUE THREAD

**Issue by fboucher** [sam-cogan/arm-snippets-vscode#5]
When you add a Storage account 'arm-stg' to your json file it generates this

    {
        "type": "Microsoft.Storage/storageAccounts",
        "apiVersion": "2018-07-01",
        "name": "StorageAccount1",
        "location": "[resourceGroup().location]",
        "tags": {
            "displayName": "StorageAccount1"
        },
        "sku": {
            "name": "Standard_LRS"
        }
        "kind": "StorageV2",
    }

It's not a valide json. The error is at the last comma of the last line:  "kind": "StorageV2"**,**

**Potential solution:**
I think the error comes from here: https://github.com/sam-cogan/azure-xplat-arm-tooling/blob/db4d9be7921268861acef33326151a47aa24bb85/VSCode/armsnippets.json#L1281

but I'm not sure how to test it.

**Comment by sam-cogan** [comment]
Should be sorted now, sorry for the delay.

**Comment by sam-cogan** [comment]
Should be sorted now, sorry for the delay.
